export const plans = [
    {
        title: "Free",
        description: "Perfect for getting started with issuing certificates.",
        price: 0,
        features: [
            "Issue up to 5 certificates per course",
            "Create up to 5 courses",
            "Basic certificate templates",
            "Access to issuer dashboard",
            "Community support",
        ],
        plan: "free",
        maxCourses: 5,
        maxCertsPerCourse: 5,
        paymentLink: "/auth/google",
        buttonText: "Start for Free",
    },
    {
        title: "Pro",
        description: "Ideal for independent issuers or small institutions.",
        price: 15,
        features: [
            "Issue up to 50 certificates per course",
            "Create up to 20 courses",
            "Custom certificate branding (logo, colors, signature)",
            "Basic analytics (issuance stats, student tracking)",
            "Priority email support",
        ],
        plan: "pro",
        maxCourses: 20,
        maxCertsPerCourse: 50,
        paymentLink: process.env.NEXT_PUBLIC_STRIPE_PRO_PLAN!,
        buttonText: "Upgrade to Pro",
    },
    {
        title: "Power",
        description: "For organizations that issue certificates at scale.",
        price: 20,
        features: [
            "Unlimited certificates per course",
            "Unlimited courses",
            "Team access (multiple issuer accounts)",
            "24/7 phone & email support",
            "Early access to new features",
        ],
        plan: "power",
        maxCourses: Infinity,
        maxCertsPerCourse: Infinity,
        paymentLink: process.env.NEXT_PUBLIC_STRIPE_POWER_PLAN!,
        buttonText: "Go Power",
    },
];
